# Generated by Django 5.1.4 on 2024-12-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_course_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='posts/photos/'),
        ),
    ]
